<Sensor>:
    size: 10, 10
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size

<Body>:
    size: 20, 10
    canvas:
        Color:
            rgba: self.color
        Rectangle:
            pos: self.pos
            size: self.size

<Center>:
    size: 1, 1
    canvas:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Ellipse:
            pos: 0, 0
            size: self.size
